import {
  FaHome,
  FaUserAlt,
  FaCog,
  FaBoxOpen,
  FaEnvelope,
  FaBlog,
  FaQuestionCircle,
  FaDollarSign,
  FaStar,
  FaBriefcase,
  FaUserTie,
  FaNewspaper,
  FaHeadset,
  FaCalendarAlt,
  FaLock,
  FaFileAlt,
  FaLifeRing,
  FaComments,
  FaTools,
  FaSitemap,
} from "react-icons/fa";

export const LINKS = [
  { text: "Home", url: "/", icon: FaHome, color: "#007bff" },
  { text: "About Us", url: "/about", icon: FaUserAlt, color: "#28a745" },
  { text: "Services", url: "/services", icon: FaCog, color: "#dc3545" },
  { text: "Products", url: "/products", icon: FaBoxOpen, color: "#ffc107" },
  { text: "Contact Us", url: "/contact", icon: FaEnvelope, color: "#17a2b8" },
  { text: "Blog", url: "/blog", icon: FaBlog, color: "#6f42c1" },
  { text: "FAQs", url: "/faqs", icon: FaQuestionCircle, color: "#e83e8c" },
  { text: "Pricing", url: "/pricing", icon: FaDollarSign, color: "#fd7e14" },
  {
    text: "Testimonials",
    url: "/testimonials",
    icon: FaStar,
    color: "#20c997",
  },
  { text: "Portfolio", url: "/portfolio", icon: FaBriefcase, color: "#343a40" },
  { text: "Careers", url: "/careers", icon: FaUserTie, color: "#6610f2" },
  { text: "News", url: "/news", icon: FaNewspaper, color: "#e83e8c" },
  { text: "Support", url: "/support", icon: FaHeadset, color: "#fd7e14" },
  { text: "Events", url: "/events", icon: FaCalendarAlt, color: "#28a745" },
  {
    text: "Privacy Policy",
    url: "/privacy-policy",
    icon: FaLock,
    color: "#007bff",
  },
  {
    text: "Terms of Service",
    url: "/terms",
    icon: FaFileAlt,
    color: "#6f42c1",
  },
  {
    text: "Help Center",
    url: "/help-center",
    icon: FaLifeRing,
    color: "#17a2b8",
  },
  { text: "Forums", url: "/forums", icon: FaComments, color: "#dc3545" },
  { text: "Resources", url: "/resources", icon: FaTools, color: "#ffc107" },
  { text: "Sitemap", url: "/sitemap", icon: FaSitemap, color: "#20c997" },
];
